apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-api
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: k8s.ukemewilson.sbs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  fast-api
                port:
                  number: 80