apiVersion: v1
kind: Service
metadata:
  name: fast-api
  namespace: fast-api-ns
spec:
  type: ClusterIP
  selector:
    app: fast-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80